filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/demo-app/*.log
    fields:
      source: demo-app
    fields_under_root: false
    multiline:
      pattern: '^\d{4}-\d{2}-\d{2}'
      negate: true
      match: after

output.logstash:
  hosts: ["logstash:5044"]

setup.kibana:
  host: "kibana:5601"

logging.level: info
logging.to_stderr: true
