use std::path::{Path, PathBuf};

use indexmap::IndexMap;

use crate::compose::types::Service;
use crate::error::Result;

const HOSTS_DIR: &str = ".apptainer-compose/hosts";

/// Generate a hosts file for service discovery.
/// Maps all service names to 127.0.0.1 so containers can reach each other
/// by service name when using host networking.
pub fn generate_hosts_file(
    project_dir: &Path,
    services: &IndexMap<String, Service>,
) -> Result<PathBuf> {
    let dir = project_dir.join(HOSTS_DIR);
    std::fs::create_dir_all(&dir)?;

    let hosts_path = dir.join("hosts");

    let mut content = String::new();
    content.push_str("# Generated by apptainer-compose\n");
    content.push_str("127.0.0.1 localhost\n");
    content.push_str("::1 localhost\n");

    for (service_name, service) in services {
        let hostname = service
            .hostname
            .as_deref()
            .unwrap_or(service_name.as_str());

        content.push_str(&format!("127.0.0.1 {service_name}\n"));
        if hostname != service_name {
            content.push_str(&format!("127.0.0.1 {hostname}\n"));
        }

        // Add container_name alias if specified
        if let Some(ref container_name) = service.container_name {
            if container_name != service_name {
                content.push_str(&format!("127.0.0.1 {container_name}\n"));
            }
        }

        // Add network aliases
        if let Some(ref networks) = service.networks {
            if let crate::compose::types::ServiceNetworks::Map(ref net_map) = networks {
                for (_net_name, net_config) in net_map {
                    if let Some(ref config) = net_config {
                        if let Some(ref aliases) = config.aliases {
                            for alias in aliases {
                                content.push_str(&format!("127.0.0.1 {alias}\n"));
                            }
                        }
                    }
                }
            }
        }
    }

    std::fs::write(&hosts_path, content)?;

    Ok(hosts_path)
}

/// Clean up generated hosts files
pub fn cleanup_hosts_files(project_dir: &Path) -> Result<()> {
    let dir = project_dir.join(HOSTS_DIR);
    if dir.exists() {
        std::fs::remove_dir_all(&dir)?;
    }
    Ok(())
}
